name: travy
description: Mobile travel app.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  google_fonts: ^3.0.1
  ionicons: ^0.2.1
  logger: ^1.1.0
  persistent_bottom_nav_bar: ^5.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/
